In [ ]:
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.impute import SimpleImputer

In [ ]:
#membaca dataset dari file ke Pandas dataFrame
ILPDdataset = pd.read_csv('ILPD.csv', delimiter=';', header=0)
x = ILPDdataset.iloc[:, :-1].values
y = ILPDdataset.iloc[:, -1].values

In [ ]:
ILPDdataset.head()

Age  Gender   TB  DB  Alkphos  Sgpt  Sgot  TP  ALB  A/G Ratio Indication
0   65  Female    7   1      187    16    18  68   33        9.0      Liver
1   62    Male  109  55      699    64   100  75   32       74.0      Liver
2   62    Male   73  41      490    60    68   7   33       89.0      Liver
3   58    Male    1   4      182    14    20  68   34        1.0      Liver
4   72    Male   39   2      195    27    59  73   24        4.0      Liver

In [ ]:
#Mengubah kelas (kolom indication dan gender dari string ke Unqiue)
ILPDdataset["Indication"] = pd.factorize(ILPDdataset.Indication)[0]
ILPDdataset["Gender"] = pd.factorize(ILPDdataset.Gender)[0]

In [ ]:
print(x)

[[65 'Female' 7 ... 68 33 9.0]
 [62 'Male' 109 ... 75 32 74.0]
 [62 'Male' 73 ... 7 33 89.0]
 ...
 [52 'Male' 8 ... 64 32 1.0]
 [31 'Male' 13 ... 68 34 1.0]
 [38 'Male' 1 ... 73 44 15.0]]


In [ ]:
print(ILPDdataset)

     Age  Gender   TB  DB  Alkphos  Sgpt  Sgot  TP  ALB  A/G Ratio  Indication
0     65       0    7   1      187    16    18  68   33        9.0           0
1     62       1  109  55      699    64   100  75   32       74.0           0
2     62       1   73  41      490    60    68   7   33       89.0           0
3     58       1    1   4      182    14    20  68   34        1.0           0
4     72       1   39   2      195    27    59  73   24        4.0           0
..   ...     ...  ...  ..      ...   ...   ...  ..  ...        ...         ...
578   60       1    5   1      500    20    34  59   16       37.0           1
579   40       1    6   1       98    35    31   6   32       11.0           0
580   52       1    8   2      245    48    49  64   32        1.0           0
581   31       1   13   5      184    29    32  68   34        1.0           0
582   38       1    1   3      216    21    24  73   44       15.0           1

[583 rows x 11 columns]


In [ ]:
#Mengubah dataFrame ke array Numpy
ILPDdataset = ILPDdataset.to_numpy()

In [ ]:
#Menghilangkan Missing value
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(ILPDdataset[:, 0:10])
ILPDdataset[:, 0:10] = imputer.transform(ILPDdataset[:, 0:10])

In [ ]:
print(ILPDdataset)

[[ 65.   0.   7. ...  33.   9.   0.]
 [ 62.   1. 109. ...  32.  74.   0.]
 [ 62.   1.  73. ...  33.  89.   0.]
 ...
 [ 52.   1.   8. ...  32.   1.   0.]
 [ 31.   1.  13. ...  34.   1.   0.]
 [ 38.   1.   1. ...  44.  15.   1.]]


In [ ]:
#Membagi dataset 466 baris data untuk training dan 117 baris data untuk testing
dataTraining = np.concatenate((ILPDdataset[0:233,:],
                               ILPDdataset[290:523]), axis=0)
dataTesting = np.concatenate((ILPDdataset[233:290,:],
                               ILPDdataset[523:583]), axis=0)

In [ ]:
print(dataTraining)
len(dataTraining)


[[ 65.   0.   7. ...  33.   9.   0.]
 [ 62.   1. 109. ...  32.  74.   0.]
 [ 62.   1.  73. ...  33.  89.   0.]
 ...
 [ 62.   1.  18. ...   4.   8.   0.]
 [ 55.   1.  44. ...  21.   4.   0.]
 [ 46.   0.   8. ...  37.   8.   0.]]


466

In [ ]:
inputTraining = dataTraining[:,0:10]
inputTesting = dataTesting[:,0:10]
labelTraining = dataTraining[:,10]
labelTesting = dataTesting[:,10]
print(labelTraining)
len(labelTraining)

[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0.
 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0.
 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1.
 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0.
 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0.
 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0.
 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0.

466

In [ ]:
model = tree.DecisionTreeClassifier()

In [ ]:
model = model.fit(inputTraining, labelTraining)

In [ ]:
hasilPrediksi = model.predict(inputTesting)
print("label sebenarnya ", labelTesting)
print("hasil prediksi :",hasilPrediksi)

label sebenarnya  [0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0.
 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0.
 0. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
hasil prediksi : [1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0.
 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1.
 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("prediksi benar: ", prediksiBenar,"data")
print("prediksi salah: ", prediksiSalah,"data")
print("akurasi:", prediksiBenar/(prediksiBenar+prediksiSalah)
      * 100, "%")

prediksi benar:  81 data
prediksi salah:  36 data
akurasi: 69.23076923076923 %
